Repository doka-guide/y-doka.site, pull requests merged in 2020-12, with the labels that each got.

#305 Заменяет тэг на тег
  src/posts/html/doka/audio.md
  src/posts/html/doka/p.md
  src/posts/js/doka/dom.md
  src/posts/js/doka/element.md
Labels: доработка, контент

#206 Добавляет статью о рекурсии
  src/assets/images/posts/js/recursion/base-case.png
  src/assets/images/posts/js/recursion/block-scheme.png
  src/assets/images/posts/js/recursion/call-stack-exceeded.jpg
  src/assets/images/posts/js/recursion/factorial.png
  src/assets/images/posts/js/recursion/mirror-corridor.jpg
  src/assets/images/posts/js/recursion/serpinsky-triangle.png
  src/posts/js/doka/function.md
  src/posts/js/long/recursion.md
Labels: JS, контент, лонгрид

#329 добавляет проверку на наличие элемента
  src/assets/scripts/modules/search.js
Labels: 🔥 bug

#322 Добавляет раздел «Инструменты» со статьями
  src/assets/images/posts/js/code-review/example.png
  src/assets/images/posts/js/git-cli/high-level.png
  src/assets/images/posts/js/git-cli/merge.png
  src/assets/images/posts/js/static-types/extra-step.png
  src/assets/images/posts/js/version-control/git_01.png
  src/assets/images/posts/js/version-control/git_02.png
  src/includes/aside/aside.njk
  src/includes/authors/kamyshev/author.njk
  src/includes/authors/kamyshev/in-work.njk
  src/includes/postlists/js/tools.njk
  src/pages/nav-pages/js.njk
  src/pages/nav-pages/jsTools.njk
  src/posts/js/tools/bundlers.md
  src/posts/js/tools/code-review.md
  src/posts/js/tools/git-cli.md
  src/posts/js/tools/nodejs-tooling.md
  src/posts/js/tools/nodejs.md
  src/posts/js/tools/package-managers.md
  src/posts/js/tools/static-analysis.md
  src/posts/js/tools/static-types.md
  src/posts/js/tools/tools.json
  src/posts/js/tools/version-control.md
Labels: JS, контент, лонгрид

#213 Added contributors block
  src/assets/icons/facebook.svg
  src/assets/icons/twitter.svg
  src/assets/styles/components/_article.scss
  src/assets/styles/components/_contributors.scss
  src/assets/styles/main.scss
  src/includes/contributors/contributors-list.njk
  src/includes/contributors/contributors.njk
  src/layouts/post.njk
  src/people/ABatickaya/index.md
  src/people/grachev/index.md
  src/posts/html/doka/a.md
  utils/filters.js
Labels: вёрстка

#316 Добавляет статью о подгрузке контента по скроллу
  src/assets/images/posts/js/infinite-scroll/data-template.jpg
  src/assets/images/posts/js/infinite-scroll/fetch-inject.jpg
  src/assets/images/posts/js/infinite-scroll/paginator.png
  src/assets/images/posts/js/infinite-scroll/position-tracking.jpg
  src/assets/images/posts/js/infinite-scroll/switter.jpg
  src/posts/js/long/infinite-scroll.md
Labels: JS, контент, лонгрид

#337 Fix/Временно скрывает блок контрибьюторов
  src/layouts/post.njk
Labels: 🔥 bug

#355 правит name в статье про порядок выполнения
  package-lock.json
  src/posts/js/doka/execution-order.md
Labels: 🔥 bug

#192 Новая дока по `<fieldset>`
  src/posts/html/doka/fieldset.md
Labels: HTML, контент, статья

#349 Убирает папку `posts` из URLов статей
  src/posts/posts.json
  utils/filters.js
Labels: обсуждение

#373 Добавил статью про Element.classList
  src/posts/js/doka/element-classlist.md
Labels: JS, контент, статья

#387 Правит написание ECMAScript
  src/posts/js/long/language-versions.md
  src/posts/js/long/modules.md
Labels: JS, доработка

#388 Убирает код с названий библиотек
  src/posts/js/doka/array-map.md
  src/posts/js/long/ref-type-vs-value-type.md
Labels: JS, доработка, контент

#207 Вносит правки в <a>
  src/includes/authors/pepelsbey/author.njk
  src/includes/authors/pepelsbey/in-work.njk
  src/posts/html/doka/a.md
Labels: HTML, доработка, контент

#325 Добавляет статью о селекторе по атрибуту
  src/posts/css/doka/attribute-selector.md
Labels: CSS, контент, статья

#341 Вносит правки в hidden
  src/posts/html/doka/hidden.md
Labels: HTML, доработка, контент

#377 Добавляет статью о селекторе по классу
  src/posts/css/doka/class-selector.md
Labels: CSS, контент, статья

#389 Правит использование тире и дефисов
  src/posts/README.md
  src/posts/css/doka/color.md
  src/posts/css/doka/content.md
  src/posts/css/doka/list-style-image.md
  src/posts/css/doka/transition-duration.md
  src/posts/css/doka/transition.md
  src/posts/css/long/grid-guide.md
  src/posts/html/doka/blockquote.md
  src/posts/html/doka/label.md
  src/posts/js/doka/array-reduce.md
  src/posts/js/doka/arrays.md
  src/posts/js/doka/dom.md
  src/posts/js/doka/element-classlist.md
  src/posts/js/doka/element-keydown-keyup.md
  src/posts/js/doka/element.md
  src/posts/js/doka/fetch.md
  src/posts/js/doka/for.md
  src/posts/js/doka/function.md
  src/posts/js/doka/json.md
Labels: доработка, контент

#307 Добавляет руководство для авторов
  WRITING.md
  src/assets/images/docs/writing/callouts.png
Labels: для основной команды, инструкция

#401 Удаляет закомментированный код
  src/assets/styles/base/_focus.scss
  src/assets/styles/utils/_prism.scss
Labels: доработка

#402 Подчищает JS-заголовки от лишнего
  src/posts/js/doka/for.md
  src/posts/js/doka/function.md
  src/posts/js/doka/getelementbyid.md
  src/posts/js/doka/getelementsbyclassname.md
  src/posts/js/doka/getelementsbytagname.md
  src/posts/js/doka/index-of.md
Labels: JS, доработка, контент

#406 Собирает всё про шрифты в одном месте
  src/assets/styles/base/_fonts.scss
  src/assets/styles/components/_article.scss
  src/assets/styles/utils/_variables.scss
Labels: доработка

#371 Статья про теги таблицы
  src/assets/images/posts/tables/table1.jpg
  src/posts/html/doka/tables.md
Labels: HTML, контент, лонгрид

#423 Добавляет ссылку на Руководство контрибьютора
  README.md
Labels: доработка

#418 Убирает CSS-вьюпорт
  src/assets/styles/base/_reboot.scss
Labels: доработка

#416 Правит вложенность ссылок
  src/pages/nav-pages/all.njk
Labels: 🔥 bug

#417 Подчищает шаблон и переносит метрику
  src/includes/meta.njk
  src/layouts/base.njk
  src/layouts/main.njk
  src/layouts/nav-page.njk
  src/layouts/no-aside.njk
Labels: 🔥 bug
