Repository doka-guide/y-doka.site, pull requests merged in 2021-03, with the labels that each got.

#609 Расписывает блок с возможными значениями
  src/posts/css/doka/grid.md
Labels: Задачи по редактуре

#613 Рефакторинг статьи про <div>
  src/demos/div/index.njk
  src/posts/html/doka/div.md
Labels: Задачи по редактуре

#604 Добавляет обзорную-вводную статью о тестировании
  src/assets/images/posts/js/testing/testing-pyramid.png
  src/posts/js/long/how-to-test-and-why.md
Labels: Контент, Лонгрид

#644 Правит ссылку на код-ревью
  src/posts/js/tools/git-cli.md
Labels: 🔥 bug 🐞
