Repository doka-guide/y-doka.site, pull requests merged in 2021-01, with the labels that each got.

#424 Добавляет статью про touch
  src/posts/js/doka/element-touch.md
Labels: JS, контент, статья

#188 Добавляет в доку статью о селекторе по тегу
  src/posts/css/doka/tag-selector.md
Labels: CSS, контент, статья

#367 Добавляет статью про Agile
  src/assets/images/posts/js/agile/kanban.png
  src/assets/images/posts/js/agile/waterfall.png
  src/posts/js/tools/agile.md
Labels: JS, контент

#368 Добавляет статью про Webpack
  src/assets/images/posts/js/webpack/bundle.png
  src/posts/js/tools/webpack.md
Labels: JS, контент
